// <auto-generated />
namespace MyCRUD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class myCRUDmigrationsetup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(myCRUDmigrationsetup));
        
        string IMigrationMetadata.Id
        {
            get { return "201709061708494_my CRUD migration set up"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
